### ISSUE TITLE
Update the workflow to use new version of song/score modules

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo-workflows/dna-seq-processing-wfs#68]
- New version of song/score modules will provide the capability to use the container, container_registry, container_version which are provided by the users. 
- This repo was migrated from [old repo](https://github.com/icgc-argo/dna-seq-processing-wfs), will need to update the repo info in the code.

**Comment by b-f-chan** [comment]
Now in a feature branch awaiting release, testing has been completed

**Comment by puneet-oicr** [comment]
Can be closed after a release is created. Linda is targeting today.

**Comment by lindaxiang** [comment]
New workflow release with version [1.9.1 ](https://github.com/icgc-argo-workflows/dna-seq-processing-wfs/releases/tag/1.9.1)has been created, closing this ticket.
